### ISSUE TITLE
Tìm ý tưởng

### ISSUE THREAD

**Issue by haunt98** [nmcntt2-cntn2016/project1-the-bananas#1]
# Yêu cầu:

- Vấn đề gì ?
- Đối tượng nào?
- Tại sao ? 
- Giải pháp ?

**Comment by haunt98** [comment]
# Ý tưởng:  Tạo App/Web tạo/tìm việc thời vụ.
_(Công việc thời vụ: chỉ làm trong một thời gian nhất định. Ví dụ nhà hàng có bữa đông khách cần người.)_

- **Ý nghĩa:** Giúp các sinh viên có thể kiếm tiền bằng cách làm thêm.
- **Mô tả:** Các nhà hàng, khu vui chơi, nhà tổ chức sự kiện có thể đăng tin kiếm người làm gấp; các sinh viên có thể tìm việc; sinh viên chỉ cần một số thông tin cơ bản như: Họ và tên, năm sinh, khả năng; có khả năng kiếm việc nhanh nếu cả 2 bên đồng ý.

**Comment by SummerSad** [comment]
# Ý tưởng 2: Tạo App/Web cung cấp thực phẩm sạch
_(Thực phẩm sạch như cá sạch, rau sạch, thịt sạch, với chất lượng đảm bảo và nguồn gốc rõ ràng)_

- **Ý nghĩa:** Giúp người tiêu dùng tiếp cận với nguồn thực phẩm an toàn trong tình trạng thực phẩm bẩn tràn lan trên thị trường.
- **Mô tả:** ...

**Comment by SummerSad** [comment]
# Ý tưởng 3: Cây bút thông minh
...

**Comment by akiabalo1706** [comment]
Web về công việc á. Tui thấy có thiết thực. Còn web cung cấp thực phẩm, chẳng phải ngoài thị trường đã có rất nhiều rồi hay sao? chúng ta có nên thêm một vài chức năng mới không?

**Comment by akiabalo1706** [comment]
Ngoài nguồn gốc, xuất xứ, cách bảo quản rồi còn gì nữa không?

**Comment by akiabalo1706** [comment]
ủa khoan còn cái công việc là có tạo điều kiên cho làm dài lâu không vậy?

**Comment by haunt98** [comment]
@akiabalo1706 

- Công việc thời vụ mà, trong khoảng thời gian nhất định: 2->3 ngày.
- Còn ý tưởng thực phẩm sạch: mình có thể khảo sát và đưa ra nhiều nhận định thực tế kĩ hơn như @thanhnguyenduy2304  đã nói.

**Comment by daohoang18398** [comment]
# Ý tưởng: Bảng cảm biến chữ viết + App kết nối bảng vs Máy tính, Smart Phone
## Mô tả đề tài? 
 
Do hiện nay lớp học tại các trường cấp 3, đại học ở nước ta khá đông, việc một lớp học lớn với số lượng lớn học sinh là điều không tránh khỏi. Không thiếu những lời than phiền về việc không nhìn thấy bảng. Do đó, mình muốn xây dựng một sự kết nối giữa tấm bảng ghi với chiếc Smart phone của mỗi học sinh, qua đó những bạn học sinh k nhìn thấy bảng có thể nhìn vào smart phone mà có thể theo dõi những gì ghi trên bảng.

## Tại sao chọn đề tài:

- Giải quyết được vấn đề sinh viên không nhìn được bảng do lớp học lớn, hạn chế việc chụp hình bảng trong quá trình học gây khó chịu cho giáo viên, sinh viên ngồi ở xa có thể nhìn được những gì ở trên bảng thông qua thiết bị di động.
- Có thể sử dụng trong phòng học chuyên dụng cho làm việc nhóm, các nhóm sinh viên có thể ghi lên các bảng được theo xung quanh tường khi làm việc, giáo viên có thể theo dõi nhưng gì được ghi trên bảng của tất cả các nhóm mà chỉ cần nhìn vào laptop.

## Đối tượng hướng tới:

- Học sinh, sinh viên
- Giáo viên
- Trở thành một thiết bị cho các phòng thuyết trình, làm việc nhóm

## Làm như thế nào?

- Làm một chiếc bảng kính, có thể cảm nhận được khi ta viết bút lông trên bảng, "chụp"(mô phỏng) lại những gì ghi trên bảng.
- Thông qua thiết bị của bảng kết nối mạng, có thể tải lên hình ảnh của tấm bảng lên app chuyên dụng.
- Sử dụng các thiết bị di động(smart phone, laptop,...) kết hợp vs app của bảng sẽ có thể xem được hình ảnh bảng, hình ảnh sẽ được cập nhật liên tục trong quá trình sử dụng.

**Comment by haunt98** [comment]
@daohoang18398 ông có thể mô tả rõ hơn cách hoạt động của cây bút được không? cấu tạo chẳng hạn?

**Comment by akiabalo1706** [comment]
tui chưa hiểu rõ ý của ông lắm??

**Comment by daohoang18398** [comment]
Không tui đang làm cái bảng bằng kính, nó cảm nhận được những thứ ghi trên nó! sau đó nó sẽ tải lên mạng những hình ảnh sau khi mô phỏng tấm bảng, mọi người zo app coi thôi

**Comment by akiabalo1706** [comment]
à là chuyển những thứ trên bảng vào điện thoại của mỗi sinh viên qua 1 cái app??

**Comment by thanhnd0101** [comment]
# Ý tưởng: Tạo App/Web cung cấp thực phẩm sạch
## Vấn đề: 
- Nhu cầu thực phẩm sạch, đảm bảo chất lượng ngày càng trở nên rộng rãi ở khắp nơi
## Mô tả: 
- Tạo ra một trang web và app mobile kinh doanh thực phẩm sạch gồm rau, củ, quả, các loại thịt, cá,...
## Các mục cần xác định rõ ràng:
- Nơi sản xuất hay vùng cung cấp(có hình ảnh thực tế tại nơi sản xuất)— Thông qua các chuẩn kiểm định về an toàn thực phẩm, vệ sinh nơi sản xuất
- Ngày sản xuất 
- Hạn sử dụng
- Cơ chế bảo quản từ nơi sản xuất đến kho cất giữ
- Có cơ chế đặt hàng online, ship tận nhà 
- Review của khách hàng về sản phẩm
- Dịch vụ hậu mãi cho khách thành viên
- Có cơ chế giới thiệu ngẫu nhiên món ăn chế biến từ sản phẩm(link đến các trang dạy nấu ăn) khi khách hàng tham khảo sản phẩm.
- Đền bù thiệt hại khách hàng khi sản phẩm không đúng như trình bày

**Comment by thanhnd0101** [comment]
Cùng ý tưởng của Hoàng

Mô tả:
— Tạo ra 2 thiết bị và 1 cây bút 
— 2 thiết bị đặt chéo nhau,1 thiết bị đặt làm gốc 0(0,0) định vị thiết bị còn lại tạo nên 1 mặt diện tích hình chữ nhật, hình chữ nhật sẽ được chia ra thành các ô nhỏ(mỗi ô có tọa độ (x,y)) .
—Cây bút là 1 thiết bị phát ra sóng, và 2 thiết bị kia sẽ nhận sóng để định vị vị trí đầu bút. Trong đầu bút sẽ có 1 điểm cảm ứng.
— Khi viết, bút tỳ làm kích hoạt điểm cảm ứng, 2 thiết bị sẽ bắt đầu ghi nhận và lưu lại những vị trí dời của đầu bút, từ đó vẽ lên các nét và lưu data vào 1 thiết bị. Thiết bị đó sẽ phát mô phỏng được lưu ra các smartphone, tablet trong phòng học. 
— Trên thiết bị lưu sẽ có 1 nút clear để giảng viên xóa dữ liệu mô phỏng cũ đã được lưu khi giảng viên muốn xóa bài giảng để ghi tiếp tục bài goảng mới.
— Tất cả sóng ở đây đều sử dụng Buetooth Low energy.
Tổng lại: 2 thiết bị sẽ định vị cây bút và mô phỏng độ dời đầu cây bú́t trên bảng được ghi trên bảng và mô phỏng lại rồi pháy ra cho cái smartphone, tablet của sinh viên
