### ISSUE TITLE
Bản phảo trang home của trang web thời vụ chúng ta

### ISSUE THREAD

**Issue by thanhnd0101** [nmcntt2-cntn2016/project1-the-bananas#12]
[demoweb.pptx](https://github.com/nmcntt2-cntn2016/project1-the-bananas/files/901589/demoweb.pptx)

**Comment by daohoang18398** [comment]
![slide1](https://cloud.githubusercontent.com/assets/26211789/24763967/1cdf0b96-1b1d-11e7-95f2-a7c775be0e15.PNG)
![slide2](https://cloud.githubusercontent.com/assets/26211789/24763966/1cde7f6e-1b1d-11e7-9591-e235b7045cc9.PNG)
Demo giao diện người tìm việc!

**Comment by haunt98** [comment]
Đã add toàn bộ vào website ^^
