### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by daohoang18398** [nmcntt2-cntn2016/project1-the-bananas#13]
![bananas poster](https://cloud.githubusercontent.com/assets/26211789/24741072/93fe696e-1ace-11e7-94b0-3c3068ac9f60.png)

**Comment by daohoang18398** [comment]
[2.docx](https://github.com/nmcntt2-cntn2016/project1-the-bananas/files/901837/2.docx)

**Comment by daohoang18398** [comment]
2/Tìm công việc nhanh chóng, tiện lợi.
Tìm kiếm công việc theo thứ tự khung giờ và địa điểm.
Công việc đa dạng, lương bổng hợp lý.

3/Đăng kí nhận công việc mình ưng ý đơn giản, dễ dàng, mọi thủ tục để thực hiện trên website.
Có thể hủy đăng kí nếu cảm thấy không thích công việc trong một khoảng thời gian website qui định.


4/Sau khi đã quyết định chắc chắn nhận công việc, sẽ có một hợp đồng online gửi đến để bạn chấp nhận, nhằm bảo vệ quyền lợi cho bạn khi làm việc.
Nếu vi phạm hợp đồng thì sẽ phải bồi thường.


7/Sau khi làm việc, bạn có thể lên website để phản hồi lại về công việc bạn làm như thế nào, có đúng thỏa thuận, có nhận đầu đủ lương.
Nếu có sự cố, dựa vào hợp đồng website sẽ bảo vệ quyền lợi cho bạn

**Comment by haunt98** [comment]
ok t đã copy vào web xong

**Comment by daohoang18398** [comment]
<img width="1716" alt="poster_new1" src="https://cloud.githubusercontent.com/assets/26211789/24763873/dec867c6-1b1c-11e7-8494-c10fbabf2354.png">
Poster sau khi chỉnh sửa chiều nay!

**Comment by daohoang18398** [comment]
<img width="1716" alt="poster_new1" src="https://cloud.githubusercontent.com/assets/26211789/24763889/f2136664-1b1c-11e7-835f-fd01f56fb706.png">
Poster sau khi chỉnh sửa chiều nay!!!

**Comment by haunt98** [comment]
Đã add vào website ^^
