### ISSUE TITLE
Sơ thảo

### ISSUE THREAD

**Issue by akiabalo1706** [nmcntt2-cntn2016/project1-the-bananas#15]
[Sơ thảo.pdf](https://github.com/nmcntt2-cntn2016/project1-the-bananas/files/907477/S.th.o.pdf)

**Comment by akiabalo1706** [comment]
# Mở đầu 
Tiền không phải là quan trọng nhất nhưng không thể phủ nhận nó ít nhiều chi phối cuộc sống của mỗi người và sinh viên cũng không phải là ngoại lệ. Vấn đề thu nhập cũng như trang trải cho những chi tiêu hằng ngày cũng là một vấn đề đáng quan ngại.
# Đặt vấn đề
Đặt câu hỏi: Có bạn nào ở đây muốn tìm công việc để kiếm thêm thu nhập nhưng lại không tìm được vì vướng thời khóa biểu học dày đặt?
Vấn đề hiện tại là các sinh viên, học sinh có mong muốn tim được việc làm để trang trải cuộc sống, giúp đỡ gia đình. Tuy nhiên công việc toàn thời gian cũng như part-time có thể không thuận lợi vì phải đảm bảo vấn đề học tập => CÔNG VIỆC THỜI VỤ.
Các nhà hàng, khu vui chơi… vào những ngày lễ số lượng khách tăng đáng kể và để đảm bảo chất lượng phục vụ, họ thuê thêm những nhân viên. Thế nhưng họ lại không muôn thuê nhân viên lâu dài vì những nhân viên đó chỉ thực sự cần thiết vào những ngày lễ và sự kiện lớn. Và vì thế những CÔNG VIỆC THỜI VỤ được tạo ra.
# Giải thích
Để các bạn hiểu rõ hơn, CÔNG VIỆC THỜI VỤ là những công việc chỉ làm trong 1-2 ngày hoặc vài giờ và sau đó tiền công được nhận sau khi hoàn thành công việc. Phục vụ ở những nhà hàng, cộng tác viên ở những chương trinh ca nhạc…
# Giải pháp
Và những lí do trên, tụi mình đã tạo ra EzMoney. EzMoney là website cầu nối giữa sinh viên và nơi tuyển dụng.Vì vậy đối tượng tụi mình hướng đến, thứ nhất sẽ là sinh viên, học sinh và những người muốn kiếm thêm thu nhập,thứ 2 những công việc thời vụ. EzMoney sẽ cung cấp một quy mô tìm kiếm nhân sự rộng lớn thông qua Internet, một nơi tổng hợp những công việc thời vụ phù hợp với thời gian của bản thân, đảm bảo những lợi ích cho cả sinh viên và nơi tuyển dụng.
## Lợi ích của sinh viên là 
Vì EzMoney sẽ tập trung vào những công việc thời vụ nên sẽ giúp cho người dung tìm được thêm công việc để trang trải thu nhập. 
Tạo một lựa chọn mở cho sinh viên về thời gian làm việc, đa dạng và linh động.
Việc tìm việc thông qua facebook đối với một công việc thơi vụ đôi khi cũng mang mại một số mạo hiểm.Một nơi tổng hợp những công việc sẽ giúp bạn dễ dàng tìm việc và tìm hiểu về những công việc khác nhau.
Vấn đề hiện tại là nếu bạn muốn ứng tuyển vào một công việc, bạn phải hoàn thành thủ tục giấy tờ trực tiếp. Trao đổi thông tin,thủ tục của một công việc thời vụ hoàn toàn được thực hiện thông qua EzMoney =>  tiết kiệm thời gian.Tuy nhiên, sẽ vẫn đảm bảo lợi ích của đôi bên bắng việc một hợp đồng online sẽ được tạo ra để đảm bảo quyền lợi tôt nhất cho cả hai bên.
## Lợi ích của nơi tuyển dụng là
Miễn phí đăng tin tìm việc làm trên website, tiết kiệm chi phí tuyển dụng.
Thông tin nhân viên làm việc sẽ được cung cấp rõ ràng nếu có vấn đề xảy ra.
Tìm kiếm nhân sự một cách nhanh chóng.
# Trách nhiệm
Tuy nhiên, để mang lại lợi ích cho cả sinh viên và người tuyển dụng một cách chu đáo nhất, 2 bên cần thực hiện đầy đủ trách nhiệm của mình.
## Đối với sinh viên:
Cung cấp đầy đủ thông tin cho website để đảm bảo quyền lợi.
Làm việc nghiêm túc, đúng giờ, tác phong chỉnh chu.
Hiểu rõ và thực hiện đúng hợp đồng của 3 bên.
## Đối với nơi tuyển dụng:
Cung cấp thông tin về công việc, nhân lực,..
Trả đúng số lương đã thỏa thuận.
Giao đúng công việc, đảm bảo quyền lợi người đi làm, không lạm dụng, bóc lột,…
Hiểu rõ và thực hiện đúng hợp đồng của 3 bên.
# Mô hình
Vậy mô hình hoạt đông của EzMoney diễn ra như thế nào.
## Của Sinh viên
- Mỗi người dung sẽ có một tài khoản có chứa thông tin cá nhân của bản thân.
- Tìm công việc thích hợp sau đó apply vào công việc đó.
- Việc tìm công việc sẽ được săp xếp theo ngày và địa điểm. Đồng thời những công việc có thời gian đến ngày cần sẽ được đặt lên đầu trang – HURRY.
- Việc apply sẽ được diễn ra ở 2 trạng thái là HÀNG CHỜ và ĐÃ KÝ KẾT.
- Nếu công việc bạn apply đã chuyển sang trạng thái ĐÃ KÝ KẾT, vào đúng ngày giờ đó, chỉ cần hoàn thành công việc là bạn đã có thể nhận được tiền công.
- Gửi feedback.
## Của bên tuyển người
- Tạo tài khoản của cá nhân hoặc công ty
- Tạo công việc thời gian địa điểm số lượng rõ ràng
- Accept bla bla "" 
- Trả tiền bla bla ""

**Comment by haunt98** [comment]
Ok t sẽ sửa trực tiếp vào của ông

**Comment by akiabalo1706** [comment]
Bạn có muốn thêm ý muốn mình trình bày sâu hơn vào ý gì không?

**Comment by haunt98** [comment]
@thanhnguyenduy2304  @daohoang18398 vào bổ sung đi kìa

**Comment by thanhnd0101** [comment]
tuyệt vời
