### ISSUE TITLE
Trả lời câu hỏi của thầy.

### ISSUE THREAD

**Issue by haunt98** [nmcntt2-cntn2016/project1-the-bananas#2]
## Khó khăn :
- [x] Người đăng việc có ích lợi gì? Lúc cần người thì họ sẽ thường làm gì?
- [x] Người tìm việc sẽ được đảm bảo những gì? 
- [x] Người tìm việc hiện đang tìm việc trên những kênh nào? Giải pháp đưa ra sẽ giải quyết những vấn đề gì cho họ? 
- [x] Có ai đã làm hay chưa và so sánh?

**Comment by akiabalo1706** [comment]
2. Người tìm việc sẽ được đảm bảo những gì?
- Người tìm việc, đối tượng chính là sinh viên, sẽ được bảo đảm về tiền công cho công việc mà mình nhận và tiền công sẽ được giao ngay cho sinh viên trong vòng 24h nếu hoàn thành công việc. Hệ thống sẽ giúp cho sinh viên tìm được công việc nhanh chóng hơn và giảm thiểu tối đa rủi ro bị lừa gạt trên mạng về vấn đề việc làm.

**Comment by thanhnd0101** [comment]
Theo tui thấy người đăng việc có thể tìm người có khả năng làm việc một cách hiệu quả, nhanh chóng trong thời gian ngắn. 
Thường thì người tìm việc sẽ dựa vào sự quen biết để tìm được người làm việc, nếu như vậy thì sẽ tốn nhiều thời gian và tiền hoa hồng trung gian.

**Comment by haunt98** [comment]
Hiện tại có nhiều trang web tìm kiếm việc làm trên mạng:
https://www.vietnamworks.com/
https://www.jobstreet.vn/

Nhưng những trang web này tập trung vào các việc làm dài hạn. Vẫn có những việc làm thời vụ, nhưng sơ sài và thiếu thông tin. Đa số chỉ toàn là những dòng text và một sdt.

**Comment by haunt98** [comment]
- Trong khi đó giải pháp đưa ra sẽ giới thiệu các công việc thời vụ một cách trực quan sinh động hơn, cùng với đó là nhiều thông tin để người dùng xem xét. 
- Bên cạnh đó, giải pháp sẽ xây dựng cách đánh giá cho cả người tìm việc và người đăng tin tìm việc theo thang điểm.

**Comment by daohoang18398** [comment]
## 3/Người tìm việc hiện đang tìm việc trên những kênh nào? Giải pháp đưa ra sẽ giải quyết những vấn đề gì cho họ?
- Người tìm việc hiện tại đang tìm việc qua các trang mạng, qua mạng xã hội(facebook), qua tờ rơi, qua tv báo đài! 
- Giải pháp về việc làm một website việc làm sẽ tạo cho mọi người một kênh thông tin việc làm đa dạng và tin cậy, sẽ chắt lọc những công việc phù hợp cho mỗi người. Trang web sẽ làm rõ những điều kiện cần cho công việc một cách rõ ràng, giúp người tìm việc không  mất thời gian vào việc tìm kiếm những công việc đòi hỏi điều kiện mà mình không đủ. Trang web cũng sẽ cung cấp một cách tưởng minh về công việc phải làm và lương bổng cho công việc.

**Comment by daohoang18398** [comment]
## 1/ Người đăng việc có ích lợi gì? Lúc cần người thì họ sẽ thường làm gì?
- Lợi ích của người đăng tìm việc
