### ISSUE TITLE
WorkFlow và hợp đồng sơ thảo

### ISSUE THREAD

**Issue by thanhnd0101** [nmcntt2-cntn2016/project1-the-bananas#8]
[Workflow.pdf](https://github.com/nmcntt2-cntn2016/project1-the-bananas/files/875304/Workflow.pdf)

**Comment by thanhnd0101** [comment]
Đây là workflow và hợp đồng sơ thảo. nếu có thêm gì t sẽ úp lên cho mọi người xem
Hiện tại còn cái "Thỏa thuận online" nữa. I am thinking

**Comment by thanhnd0101** [comment]
bản ppt 
[Doan1.pptx](https://github.com/nmcntt2-cntn2016/project1-the-bananas/files/888399/Doan1.pptx)

**Comment by haunt98** [comment]
T thấy ổn r đó
